### ISSUE TITLE
TelegramX crashes in Android 4.4 when trying to play voice messages

### ISSUE THREAD

**Issue by SagePtr** [TGX-Android/Telegram-X#896]
TelegramX lost Android 4.4 compatibility after update androidx-media to 1.6.1

How to reproduce:
1. Upgrade Telegram to the latest 0.27.10.1752 on Android 4.4 (this happens automatically with Google Play).
2. Write a voice message and send it to anyone or yourself, or ask someone to send you a voice message.
3. Play it.
4. Enjoy the crash.

Error message:
```
java.lang.NoSuchMethodError:
android.media.AudioManager.generateAudioSessionId
```

This is caused by updating third_party/androidx-media to 1.6.1 in this commit: https://github.com/TGX-Android/Telegram-X/commit/795df1e8a032f904de5450fb3c8dce06ebdc80e1

The androidx-media dropped support of API Level 19 (Android 4.4) in this commit:  https://github.com/androidx/media/commit/6a9ff95bf01ae9ef62f8f82aeb109cfdb8d8bdaf (happened in 1.5.0)

Checkmate.

Not sure how to gracefully solve this problem without downgrading androidx-media back to the old version (to fix 4.4 backwards compatibility) and upgrade it only after you officially drop 4.4 support just not to leave 0.27 on Android 4.4 in the failed state.

UPD: it also crashes when trying to play any video.

**Comment by vkryl** [comment]
Downgraded to `1.4.1` in cd8e6c4.
